### ISSUE TITLE
release 2.0.2 windows got error

### ISSUE THREAD

**Issue by beansoft** [jansorg/marketplace-stats#1]
marketplace-stats.exe -plugin-id 9564 -token-file token.txt -out RNConsole_report.html
panic: time: missing Location in call to Date

goroutine 1 [running]:
time.Date(0x7e4, 0x7, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, ...)
        /usr/lib/go/src/time/time.go:1344 +0x645
github.com/jansorg/marketplace-stats/marketplace.init()
        /home/jansorg/self-employment/products/marketplace-stats/marketplace/const.go:8 +0x96

I downloads from the release page marketplace-stats_0.2.0_Windows_x86_64.tar.gz

**Comment by beansoft** [comment]
Tried 1.0, also no lucky. But the mac version works.

**Comment by jansorg** [comment]
@beansoft Thanks, that was an issue with timezone data. I've fixed that and release 0.3.0: https://github.com/jansorg/marketplace-stats/releases/tag/v0.3.0
